apiVersion: v1
kind: Service
metadata:
 name: labbservice-service
 namespace: b2
spec:
 selector:
   app: labb
 ports:
   - name: labb
     protocol: TCP
     port: 8080
     targetPort: 8080
 type: ClusterIP